name: Build and test
# À chaque push et pull requestion, l'action est activé. 

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main
jobs:
  
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Test
      run: dotnet test --no-build
      id: tests
    
    - name: Tests completed
      run: echo "All tests completed successfully"
    
    - name: Create Issue From Failed Test
      if: failure() && steps.tests.outcome == 'failure'
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_GITHUBACTION }}
      with:
        title: Tests Failed
        body: |
          The tests failed on the latest push. Please review the errors and correct them.

    - name: Commit and push if changed
      run: |
        git diff
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Updated README"
        git push
